### ISSUE TITLE
Per-Inventory output path

### ISSUE THREAD

**Issue by sinni800** [Joshuarox100/VRC-Inventory-Inventor#15]
I usually have multiple avatars per unity project and since I also copy them to a quest project regularly, I keep the inventory output in a subdirectory of the avatar.

Now, a project wide default path doesn't make a ton of sense in this case... How about being able to set the output path per inventory file? The output path could be read out of the inventory as soon as the preset is dropped into the inventory inventor settings page.

**Comment by Joshuarox100** [comment]
Hmm... not a bad idea! I'll test out this idea with a few folks when I get around to it and see how it feels.

**Comment by Joshuarox100** [comment]
This feature has been implemented into the development branch and will be included in the next release.
