### ISSUE TITLE
[Requests] Copy and paste groups/islocal option

### ISSUE THREAD

**Issue by noideaman** [Joshuarox100/VRC-Inventory-Inventor#20]
Feature 1: copying and pasting groups for easier toggle/button groups
![image](https://user-images.githubusercontent.com/39884745/124407750-ec0e5480-dd01-11eb-900a-4c951d146a52.png)

Feature 2: is local option, so toggles/buttons that are only needed for the wearer of the avatar can leverage this
![image](https://user-images.githubusercontent.com/39884745/124407855-27a91e80-dd02-11eb-9ff6-c471f7f34c56.png)

I am currently modifying this on the haptic vest as it that item crashes a very small set of people, [link to issue](https://github.com/HerpDerpinstine/VRCBhapticsIntegration/issues/6).

**Comment by noideaman** [comment]
also hi josh

**Comment by Joshuarox100** [comment]
1. is already implemented into the next upcoming  release of Inventory Inventor.
2. is already a feature. Set the sync of the local toggles to “Off” to make them local only.

Let me know if you have any other concerns or requests! If not, I will close this issue after 3 days.

**Comment by noideaman** [comment]
Ah that is what sync means. cool TY
