### ISSUE TITLE
Invetory preset no longer recognised after update to 1.3.3

### ISSUE THREAD

**Issue by Lupinixx** [Joshuarox100/VRC-Inventory-Inventor#30]
After doing the update to 1.3.3 this morning (not sure what version i came from, the newest before this version...) my preset is no longer recognised by the tool. I cannot drag drop it in the preset box, neither is it displayed in the list of presets. i am on unity 2019.4.31f

**Comment by Joshuarox100** [comment]
Ah damn. You're right. I moved the repo to its own Unity project and I didn't realize that the GUID's for the scripts were reset somewhere along that process. I've replaced the Unity package in the release with a fixed version, could you download that and see if they're still broken?

**Comment by Lupinixx** [comment]
Yes this fixed it, thanks for the quick update!
